### ISSUE TITLE
ERROR: from get_position import Vocab_post

### ISSUE THREAD

**Issue by Dyleaf** [NLPWM-WHU/BiGCN#4]
I can‘t find get_position.py in your code, could you provide this file in your code ?

**Comment by NLPWM-WHU** [comment]
I’m sorry that I forgot to upload this part of the code, I have uploaded it now, please check

**Comment by NLPWM-WHU** [comment]
> I can‘t find get_position.py in your code, could you provide this file in your code ?

I’m sorry that I forgot to upload this part of the code, I have uploaded it now, please check
