### ISSUE TITLE
FileNotFoundError: No such file or directory: 'datasets/semeval16/rest16_vocab_post.pkl

### ISSUE THREAD

**Issue by Kgoeson** [NLPWM-WHU/BiGCN#5]
I suffer such error when I use 'python train.py --dataset rest16 --vocab_dir datasets/semeval16/rest16_ --save True' to execute the program.

**Comment by NLPWM-WHU** [comment]
Hello, you can run the get_position.py program directly to get this file. Or it can be obtained from rest16's data set.

**Comment by NLPWM-WHU** [comment]
> I suffer such error when I use 'python train.py --dataset rest16 --vocab_dir datasets/semeval16/rest16_ --save True' to execute the program.

Hello, you can run the get_position.py program directly to get this file. Or it can be obtained from rest16's data set.
